name: sequana_chipseq

channels:
- conda-forge
- bioconda
- defaults
- r

dependencies:
- samtools>1.7
- bamtools
- bedtools
- bowtie2>=2.3
- fastqc
- subread
- fastp
- deeptools
- picard>2.20
- ucsc-bedgraphtobigwig
- homer
- macs3
- multiqc
- snakemake-minimal
- pip:
  - sequana
  - sequana-wrappers>=26.3.21

