# ============================================================================
# Config file for RNA-seq
#
# ==================[ Sections for the users ]================================
#
# One of input_directory, input_pattern and input_samples must be provided
# If input_directory provided, use it otherwise if input_pattern provided,
# use it, otherwise use input_samples.
# ============================================================================
input_directory: ""
input_readtag: _R[12]_
input_pattern: '*fastq.gz'
exclude_pattern: ~
# =========================================== Sections for the users

apptainers:
    graphviz: https://zenodo.org/record/7928262/files/graphviz_7.0.5.img
    sequana_tools: https://zenodo.org/record/18257162/files/sequana_tools_26.1.14.img
    fastqc: https://zenodo.org/record/7015004/files/fastqc_0.11.9-py3.img
    fastp: https://zenodo.org/record/7319782/files/fastp_0.23.2.img
    phantompeak: https://zenodo.org/record/7301453/files/phantompeakqualtools_1.2.2.img
    homer: https://zenodo.org/record/7305501/files/homer_4.11.0.img
    ucsc: https://zenodo.org/record/10011490/files/ucsc_3.7.7.img
    samtools: https://zenodo.org/record/7437898/files/samtools_1.16.1.img
    idr: https://zenodo.org/record/7305443/files/idr_2.0.3.img
    multiqc: https://zenodo.org/record/10205070/files/multiqc_1.16.0.img


#############################################################################
# Genome section:
#
# :Parameters:
#
# - aligner: either star, bowtie or bowtie2
# - genome_directory: directory where all indexes are written.
# - design.csv is the experimental design file
#
#   type,condition,replicat,sample_name
#   IP,    WT,   1, IP_WT_rep1
#   IP,    WT,   2, IP_WT_rep2
#   Input, WT, 1, Input_WT
general:
    aligner: bowtie2
    genome_directory:
    design_file: design.csv


#################################################################
# FastQC section
#
# :Parameters:
#
# - options: string with any valid FastQC options
#
fastqc:
    skip_fastqc_raw: True
    options: --nogroup
    threads: 4
    resources:
        mem: 4G

##########################################################################
# Fingerprints
#
# - fingerprint_bins: the number of bins that are sampled from the genome,
#     for which the overlapping number of reads is computed. (typically  500000
#     for human). Default to 5000 for bacteria
fingerprints:
    do: false
    bins: 5000


#############################################################################
# -Q should disable the quality filter
#
# Quality filtering only limits the N base number (-n, --n_base_limit) 
# meaning if 5 Ns are found, the read is discarded, 
# -q is the quality value se to Q15 to be qualified; If more than 40% of bases
# are unqualified, the read is discarded.
# You can also filter reads by average quality score using -e QUAL_score
#
# minimum length is set to 15 by default
#
# Adapter trimming is set by default. Can be disable with -A
# For adapters, this is automatic but you can be specific using 
# --adapter_sequence for read1, and --adapter_sequence_r2 for read2.
# The --cut_tail moves a sliding window from tail (3') to front, drop the bases 
# in the window if its mean quality is below cut_mean_quality, stop otherwise. 
# Use cut_tail_window_size to set the widnow size (default 4)), and 
# cut_tail_mean_quality to set the mean quality threshold (default 20)
# Other useful options: --disable_adapter_trimming and --disable_quality_filtering.
# or -n 5 (minimum number of Ns required to discard a read)
fastp:
    options: --cut_tail
    #--reads_to_process 100000
    minimum_length: 20
    adapters: ''
    quality: 15
    threads: 4
    disable_adapter_trimming: false
    disable_quality_filtering: false

#######################################################
# Quality trimming software choice
#
# software_choice__ = ["fastp"]
#
trimming:
    software_choice: fastp
    do: true


igv:
  do: true


#######################################################
# black list 
#
# use a BED3 file with tabulated file with 3 columns
# chromosome name, start position end position
# 
remove_blacklist:
    do: false
    blacklist_file: 
    threads: 1


#############################################################################
# genomesize could be hs for human, mm for mouse, otherwise provide your own.
#
# options is set to --keep-dup auto
# This option  controls the maximum same tags allowed in macs3. By default
# all are kept using 'auto'. If set to an integer, limit number of maximum
# identical tags to that integer. By default uses a pvalue of 1e-5 as pvalue
# cutoff assuming binomial distribution.
#
#
#############################################################################
macs3:
    #model_choice: 'broad'    # we do both all the time.
    #no_model: no             ## may be yes
    bandwidth: 300   # default bandwidth option --bw from macs3
    broad_cutoff: 0.05
    genome_size:       # filled automatically this may be important and need to be changed 
    options: " --keep-dup all --nomodel "  ## we keep all duplicates and let macs3 do the job
    qvalue: 0.05
    read_length: 75   # not currently used


#############################################################################
# bowtie2_mapping used to align reads against genome file
#
# :Parameters:
#
# - do: if unchecked, this rule is ignored
# - options: any options recognised by bowtie2 tool
# - threads: number of threads to be used
#
bowtie2_mapping:
    #options: "--dovetail --no-mixed --no-discordant " for paired-end data
    options: ''
    threads: 4
    genome_size_larger_than_4gb: false
    resources:
        mem: 20G

bowtie2_index:
    options: ''
    threads: 4
    resources:
      mem: 20G

# sequana implements its ow phantom peak detection but you can also
# use spp for sanity check. Results are slightly different but should convey
# the same information
phantom:
  use_spp: false

#############################################################################
# mark_duplicates (picard-tools) allows to mark PCR duplicate in BAM files
#
# :Parameters:
#
# - do: if unchecked, this rule is ignored. Mandatory for RNA-SeQC tool.
# - remove: If true do not write duplicates to the output file instead of writing them with
#            appropriate flags set.  Default value: false. This option can be set to 'null' to clear
#            the default value. Possible values: {true, false}
#
mark_duplicates:
    do: false
    remove: false ## may be True
    threads: 4
    resources:
        mem: 8G

#############################################################################
# IDR computation
#
# IDR computation can be switch off completely by setting 'do' to false.
# When computing the IDR on the replicates, you may also perform extra validation
# with the pseudo_replicates and self_pseudo_replicates IDR computation. You may 
# switch off these optional computation by setting the pseudo_replicates and/or 
# self_pseudo_replicates to 0.
idr:
  do: true
  pseudo_replicates: 1
  self_pseudo_replicates: 1
  rank: 'signal.value'  # could be p.value or q.value
  soft_idr_threshold: 0.05


#############################################################################
#  MultiQC aggregates results from bioinformatics analyses across several
#  samples into a single report.
#
# :Parameters:
#
# - options: any options recognised by multiqc
# - modules: list of modules to use. Let this empty to scan all modules
# - intput_directory: directory to scan 
# - config_file: by default, we use the multiqc_config file of the pipeline 
#     if found, otherwise fill this entry with your own.
multiqc:
    options: -p -f 
    modules: '' 
    input_directory: .
    config_file: multiqc_config.yaml
    resources:
        mem: 4G




